import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Server-side safety: ensure `localStorage` on the Node global is a working
// object. Some dev tooling may inject a stub that lacks `getItem` which
// causes `localStorage.getItem is not a function` during SSR. Replace any
// broken global.loclStorage with a safe no-op shim.
if (typeof window === "undefined") {
  try {
    const g: any = globalThis as any;
    if (g.localStorage && typeof g.localStorage.getItem !== "function") {
      // eslint-disable-next-line no-console
      console.warn("Replacing broken server global.localStorage with safe shim.", g.localStorage);
      g.localStorage = {
        getItem: (_: string) => null,
        setItem: (_: string, __: string) => undefined,
        removeItem: (_: string) => undefined,
        clear: () => undefined,
      };
    }
  } catch (e) {
    // ignore any errors while patching global
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
